name: CI
on:
    push:
        branches:
            - main
jobs:
    pulumi-push:
        name: Pulumi Push
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: pulumi/actions@v3
              with:
                  command: push
                  stack-name: prd
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
