name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/verify.yml
  deploy:
    needs:
      - validate
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_READ_WRITE_ROLE_ARN }}
          aws-region: us-west-2
          role-session-name: GitHubActions
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run deploy -- cloudflareZones emailAccounts --auto-approve
