name: CI
on:
  pull_request:
jobs:
  pulumi-preview:
    name: Pulumi Preview
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prd
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  validate:
    name: ${{ matrix.cmd }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cmd: [lint, format, type-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run ${{ matrix.cmd }}
