name: Verify

on:
  pull_request:
  workflow_call:

jobs:
  validate:
    name: ${{ matrix.cmd }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-22.04
    environment: production
    strategy:
      matrix:
        cmd: [synth, format, build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-session-name: GitHubActions
          role-to-assume: ${{ secrets.AWS_READ_ROLE_ARN }}
      - run: npm ci
      - run: npm run ${{ matrix.cmd }}
