name: Verify

on:
  pull_request:
  workflow_call:

jobs:
  validate:
    name: ${{ matrix.cmd }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cmd: [synth, format, build]
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::816188110262:role/lukeshay-cloud-terraform-state-Read
          aws-region: us-west-2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run ${{ matrix.cmd }}
